export const REPO_MAKE_REQUEST = "[REPO] MAKE_REQUEST";
export const REPO_GET_DATA = "[REPO] GET_DATA";
export const REPO_ERROR = "[REPO] ERROR";

export const ISSUES_MAKE_REQUEST = "[ISSUES] MAKE_REQUEST";
export const ISSUES_GET_DATA = "[ISSUES] GET_DATA";
export const ISSUES_GET_ALL_DATA = "[ISSUES] GET_ALL_DATA";
export const ISSUES_GET_NUM_OF_PAGES = "[ISSUES] GET_NUM_OF_PAGES";
export const ISSUES_ERROR = "[ISSUES] ERROR";

export const COMMENTS_MAKE_REQUEST = "[COMMENTS] MAKE_REQUEST";
export const COMMENTS_GET_DATA = "[COMMENTS] GET_DATA";
export const COMMENTS_ERROR = "[COMMENTS] ERROR";
